### ISSUE TITLE
Create wiki page for game universe

### ISSUE THREAD

**Issue by evinstk** [TheGovernorsJunk/CaulsCastle#19]
/cc @TheGovernorsJunk/writers

**Comment by evinstk** [comment]
@RinTinRin, @TheRagingRabbit, have you seen this issue?

**Comment by TheRagingRabbit** [comment]
Yes, I will write up a document on setting today.

**Comment by evinstk** [comment]
@RinTinRin, thanks for the write-up. Go ahead and close this issue next time so I'm notified right away&mdash;assuming you were aware of the issue of course. I know notifications haven't been reliable. I set my slack notifications to notify me on everything, and I've never missed an update. Y'all might want to do the same.
