### ISSUE TITLE
Wiki for "published" writing

### ISSUE THREAD

**Issue by evinstk** [TheGovernorsJunk/CaulsCastle#2]
Writers, you are free to collaborate in any way you see fit. I only ask that work you wish to share with the rest of the team be published to the [repository's wiki](https://github.com/TheGovernorsJunk/MetroidClone/wiki), which you should all have edit rights to. This can be any creative content whatsoever. Sketches of character designs are welcome as well.

/cc @TheGovernorsJunk/writers

**Comment by evinstk** [comment]
Anything you wish to inform other users or teams of, use the "@" syntax like I've done for the writers above. It works just like Facebook. [Our organization page](https://github.com/TheGovernorsJunk) has a list of all the users to the right. There's also a teams tab so you can reference a team.

For example, if you have a character design you'd like Ryan to take a look at, you can bring him into the conversation by typing "@GlasselRat". If you want to inform the scripters, type "@TheGovernorsJunk/scripters".

**Comment by evinstk** [comment]
I will close this issue once each of the writers has acknowledged that they've read this issue, or one of you can do it yourself if you beat me to it. Just write a comment when you've read this.

**Comment by evinstk** [comment]
And of course you're free to create any of your own issues yourselves&mdash;in fact I encourage you to. [This link](https://guides.github.com/features/issues/) provides an overview of the issues system.

**Comment by RinTinRin** [comment]
@evinstk Issue read and acknowledged!

**Comment by evinstk** [comment]
Excellent!

**Comment by evinstk** [comment]
@TheRagingRabbit, I'll take your closing and re-opening as acknowledgment :).

**Comment by TheRagingRabbit** [comment]
I'm still getting used to this system. @evinstk

**Comment by evinstk** [comment]
It'll take some time, but it'll be worth it.

**Comment by evinstk** [comment]
Bump @adian91

**Comment by adian91** [comment]
Rin and Dan, you guys have the universe. I think thats a bit too expansive for a first game the way you guys are going with it and I would rather focus on the mechanics in how the story fits into what ryan provides art work wise and tanner provides physics wise. Level design would be more fun in my mind and i can map that out
