### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by evinstk** [TheGovernorsJunk/CaulsCastle#24]
Testing communication through Slack with @TheGovernorsJunk/writers. Comment that you get a push notification.

**Comment by evinstk** [comment]
Bump @TheGovernorsJunk/writers

**Comment by evinstk** [comment]
Testing again. Did you get a notification? @TheGovernorsJunk/writers. If you don't have the word "writers" specifically, you may not get anything. Please comment here after you get a notification.

**Comment by GlasselRat** [comment]
Hello! Replies the @TheGovernorsJunk/artists 

.... Guess how I feel about my character design questions? Like nobody from the @TheGovernorsJunk/writers team ever posts. C'mon Dan and Rin, I get these notifications.

**Comment by GlasselRat** [comment]
Sorry, the "I" there was supposed to be bold, 18 point, italicized font.

**Comment by TheRagingRabbit** [comment]
@GlasselRat, my apologies I will answer your questions later today in a different thread. This thread was originally designed to test my notifications. Since I just got this message I can comfortably say they still don't work.
