### ISSUE TITLE
Artists' acknowledgement

### ISSUE THREAD

**Issue by evinstk** [TheGovernorsJunk/CaulsCastle#4]
Artists, take a look at issue #2 and read the comments concerning issues. Afterwards, write a comment here acknowledging that you have read and understand how issues work. I will then close the issue or you can close it yourself.

/cc @TheGovernorsJunk/artists

**Comment by evinstk** [comment]
@TheGovernorsJunk/artists Do you see this?

**Comment by GlasselRat** [comment]
How does this work?

@TheGovernorsJunk/artists
