### ISSUE TITLE
GitHub Questions

### ISSUE THREAD

**Issue by milmd90** [TheGovernorsJunk/CaulsCastle#9]
Hey @evinstk, where do we see what users are in each group (Eg scriptors) and which groups we are a part of?

**Comment by evinstk** [comment]
That's at [the organization's team page](https://github.com/orgs/TheGovernorsJunk/teams). Unfortunately, the mobile Github site doesn't have any links to it.

**Comment by evinstk** [comment]
Team, given that the title of this issue is a good umbrella term, let's just reopen this issue and comment here whenever there's an open GitHub question. That'll help centralize our questions and answers.

/cc @TheGovernorsJunk/artists @TheGovernorsJunk/scripters @TheGovernorsJunk/writers
